# Generated by Django 5.0.2 on 2024-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Total Price')),
                ('items', models.ManyToManyField(related_name='items', to='products.item', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
